#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;

namespace SimpleSc.Core.Models.sitecore.templates.SimpleSc.Pages
{
 	/// <summary>
	/// IStandardPage Interface		
	/// <param>Path: /sitecore/templates/SimpleSc/Pages/Standard Page</param>	
	/// <param>ID: 98ea2dda-8045-454c-88d3-3079563b53fc</param>	
	/// </summary>
	[SitecoreType(TemplateId=IStandardPageConstants.TemplateIdString )] //, Cachable = true
	public partial interface IStandardPage : IGlassBase , global::SimpleSc.Core.Models.sitecore.templates.SimpleSc.Base.IBasePage
	{
		}
	
	public static partial class IStandardPageConstants{

		public const string TemplateIdString = "98ea2dda-8045-454c-88d3-3079563b53fc";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateName = "Standard Page";
			public static readonly ID DescriptionFieldId = new ID("a1fc0c90-2e06-48c5-bde0-68f6e6577636");
		public const string DescriptionFieldName = "Description";
			public static readonly ID TitleFieldId = new ID("bd46a2bc-9cc2-434e-b07e-a7fa46f77373");
		public const string TitleFieldName = "Title";
		}
	
	/// <summary>
	/// StandardPage	/// <param>Path: /sitecore/templates/SimpleSc/Pages/Standard Page</param>	
	/// <param>ID: 98ea2dda-8045-454c-88d3-3079563b53fc</param>	
	/// </summary>
	[SitecoreType(TemplateId=IStandardPageConstants.TemplateIdString)] //, Cachable = true
	public partial class StandardPage  : GlassBase, IStandardPage 
	{
			/// <summary>
		/// The Description field.		/// <param>Field Type: Single-Line Text</param>		
		/// <param>Field ID: a1fc0c90-2e06-48c5-bde0-68f6e6577636</param>		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(IStandardPageConstants.DescriptionFieldName)]
		public virtual string Description  {get; set;}
			/// <summary>
		/// The Title field.		/// <param>Field Type: Single-Line Text</param>		
		/// <param>Field ID: bd46a2bc-9cc2-434e-b07e-a7fa46f77373</param>		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(IStandardPageConstants.TitleFieldName)]
		public virtual string Title  {get; set;}
		
	}
}
namespace SimpleSc.Core.Models.sitecore.templates.SimpleSc.Base
{
 	/// <summary>
	/// IBasePage Interface		
	/// <param>Path: /sitecore/templates/SimpleSc/Base/Base Page</param>	
	/// <param>ID: 9d991a59-49ae-44ec-9281-a45dd787860a</param>	
	/// </summary>
	[SitecoreType(TemplateId=IBasePageConstants.TemplateIdString )] //, Cachable = true
	public partial interface IBasePage : IGlassBase 
	{
			/// <summary>
		/// The Description field.		/// <param>Field Type: Single-Line Text</param>		
		/// <param>Field ID: a1fc0c90-2e06-48c5-bde0-68f6e6577636</param>		/// </summary>
		[SitecoreField(IBasePageConstants.DescriptionFieldName)]
		string Description  {get; set;}
			/// <summary>
		/// The Title field.		/// <param>Field Type: Single-Line Text</param>		
		/// <param>Field ID: bd46a2bc-9cc2-434e-b07e-a7fa46f77373</param>		/// </summary>
		[SitecoreField(IBasePageConstants.TitleFieldName)]
		string Title  {get; set;}
		}
	
	public static partial class IBasePageConstants{

		public const string TemplateIdString = "9d991a59-49ae-44ec-9281-a45dd787860a";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateName = "Base Page";
			public static readonly ID DescriptionFieldId = new ID("a1fc0c90-2e06-48c5-bde0-68f6e6577636");
		public const string DescriptionFieldName = "Description";
			public static readonly ID TitleFieldId = new ID("bd46a2bc-9cc2-434e-b07e-a7fa46f77373");
		public const string TitleFieldName = "Title";
		}
	
	/// <summary>
	/// BasePage	/// <param>Path: /sitecore/templates/SimpleSc/Base/Base Page</param>	
	/// <param>ID: 9d991a59-49ae-44ec-9281-a45dd787860a</param>	
	/// </summary>
	[SitecoreType(TemplateId=IBasePageConstants.TemplateIdString)] //, Cachable = true
	public partial class BasePage  : GlassBase, IBasePage 
	{
			/// <summary>
		/// The Description field.		/// <param>Field Type: Single-Line Text</param>		
		/// <param>Field ID: a1fc0c90-2e06-48c5-bde0-68f6e6577636</param>		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(IBasePageConstants.DescriptionFieldName)]
		public virtual string Description  {get; set;}
			/// <summary>
		/// The Title field.		/// <param>Field Type: Single-Line Text</param>		
		/// <param>Field ID: bd46a2bc-9cc2-434e-b07e-a7fa46f77373</param>		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(IBasePageConstants.TitleFieldName)]
		public virtual string Title  {get; set;}
		
	}
}
